node review-scrapper-dummy.js 	com.facebook.orca > facebook_reviews_page0
node review-scrapper-dummy.js 	com.whatsapp > whatsapp_reviews_page0
node review-scrapper-dummy.js 	co.happybits.marcopolo > marcopolo_reviews_page0
node review-scrapper-dummy.js 	com.yahoo.mobile.client.android.mail > yahoomail_reviews_page0
node review-scrapper-dummy.js 	kik.android > kik_reviews_page0
node review-scrapper-dummy.js 	com.skype.raider > skype_reviews_page0
node review-scrapper-dummy.js 	com.imo.android.imoim > imoim_reviews_page0
node review-scrapper-dummy.js 	com.google.android.apps.tachyon > tachyon_reviews_page0
node review-scrapper-dummy.js 	org.mozilla.firefox > firefox_reviews_page0
node review-scrapper-dummy.js 	com.jb.gosms > gosms_reviews_page0
node review-scrapper-dummy.js 	com.google.android.apps.fireball > fireball_reviews_page0
node review-scrapper-dummy.js 	com.viber.voip > viber_reviews_page0
node review-scrapper-dummy.js 	com.groupme.android > groupme_reviews_page0
node review-scrapper-dummy.js 	jp.naver.line.android > line_reviews_page0
node review-scrapper-dummy.js 	com.android.chrome > chrome_reviews_page0
node review-scrapper-dummy.js 	com.callapp.contacts > callapp_reviews_page0
node review-scrapper-dummy.js 	com.discord > discord_reviews_page0
node review-scrapper-dummy.js 	ru.mail > rumail_reviews_page0
node review-scrapper-dummy.js 	com.comcast.hsf > comcast_reviews_page0
node review-scrapper-dummy.js 	com.talkatone.android > talkatone_reviews_page0
node review-scrapper-dummy.js 	com.antivirus > antivirus_reviews_page0
node review-scrapper-dummy.js 	com.google.android.apps.messaging > Google_messaging_reviews_page0
node review-scrapper-dummy.js 	com.tracfone.straighttalk.myaccount > strighttalk_reviews_page0
node review-scrapper-dummy.js 	com.textmeinc.textme > textmeinc_reviews_page0
node review-scrapper-dummy.js 	com.cmcm.whatscall > whatscall_reviews_page0
node review-scrapper-dummy.js 	com.google.android.apps.hangoutsdialer > hangout_reviews_page0
node review-scrapper-dummy.js 	kr.core.technology.wifi.hotspot > wifihotspot_reviews_page0
node review-scrapper-dummy.js 	com.disney.disneygif_goo > disneygif_goo_reviews_page0
node review-scrapper-dummy.js 	com.google.android.apps.googlevoice > googlevoice_reviews_page0
node review-scrapper-dummy.js 	com.playstation.mobilemessenger > playstation_mobilemessenger_reviews_page0
node review-scrapper-dummy.js 	com.google.android.talk > google_talk_reviews_page0
node review-scrapper-dummy.js 	com.truecaller > truecaller_reviews_page0
node review-scrapper-dummy.js 	com.tencent.mm > tencent_reviews_page0
node review-scrapper-dummy.js 	com.disney.mix > disney_mix_reviews_page0
node review-scrapper-dummy.js 	net.idt.um.android.bossrevapp > bossrevapp_reviews_page0
node review-scrapper-dummy.js 	com.tracfone.tracfone.myaccount > tracfone_reviews_page0
node review-scrapper-dummy.js 	com.google.android.gm > gmail_reviews_page0
node review-scrapper-dummy.js 	com.textra > textra_reviews_page0
node review-scrapper-dummy.js 	com.cloudmosa.puffinFree > puffin_reviews_page0
node review-scrapper-dummy.js 	com.link.messages.sms > SMS_Messenger_reviews_page0
node review-scrapper-dummy.js 	org.telegram.messenger > telegram_reviews_page0
node review-scrapper-dummy.js 	com.UCMobile.intl > UCBrowser_reviews_page0
node review-scrapper-dummy.js 	com.freefacetime.videocall.android > freefacetime_reviews_page0
node review-scrapper-dummy.js 	com.moplus.moplusapp > moplus_reviews_page0
node review-scrapper-dummy.js 	com.psiphon3.subscription > phiphon_reviews_page0
node review-scrapper-dummy.js 	com.google.android.wearable.app > wearable_reviews_page0
node review-scrapper-dummy.js 	com.opera.mini.native > opera_reviews_page0
node review-scrapper-dummy.js 	com.mrnumber.blocker > mrnumber_reviews_page0
node review-scrapper-dummy.js 	mobi.mgeek.TunnyBrowser > DolphinBrowser_reviews_page0
node review-scrapper-dummy.js 	com.juphoon.justalk > justalk_reviews_page0